### ISSUE TITLE
Font Resize Component

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/tech-policy-database#57]
![Screen Shot 2019-10-31 at 1 46 47 PM](https://user-images.githubusercontent.com/1896496/67972358-e5524480-fbe4-11e9-85f5-33d9e0a118ad.png)

This component contains three buttons: one for small, medium, & large.

My recommendation is that we use CSS variables to accomplish this functionality. For example:

```scss

:root {
  --font-size--sm: 1;
  --font-size--md: 2;
  --font-size--lg: 3;
  --table-font-size: var(--font-size--sm); // When you click on one of the buttons, it should update this value. The medium button would result in this: --table-font-size: var(--font-size--md).
}

// Inside your table cell, use the calc functionality to apply the selected font-size. This will take the base font size and multiply it by the chosen amount.

// We aren't going to be able to use the placeholder functionality for this, unfortunately. So we'll need to put the typography styles for the table cells in `_table.scss` directly.

.table__cell {
  font-size: 16px;
  font-size: calc((calculate-rem(16px) * var(--table-font-size));
  line-height: 1.41;
}

```
 
We should also ask Tucker how she wants us to adjust the line-height & if it should also have a calculation.
